### ISSUE TITLE
No rare Candies

### ISSUE THREAD

**Issue by Velocity942** [Jaizu/inclement_emerald_fr#2]
NPC in Oldale Town doesn't give anything with the fr 1.10.2 patch

**Comment by Jaizu** [comment]
Is that available in the official version? I think that's from an unofficial one but I didn't check it.

**Comment by Velocity942** [comment]
Yes sorry its from the "other versions" in the discord

**Comment by Jaizu** [comment]
Closing since this is made for the official version. If you want an unofficial version with my fr style ask the guy who made that version, the repo is open for everybody to use.
